version : '3.7'
networks:
  mysql-net:
    external: true
services:
  mariadb:
        container_name : mariadb
        hostname: mariadb
        networks:
          mysql-net:
        image: registry.cn-hangzhou.aliyuncs.com/yangyuanpeng/mysql:10.4.12-utf8mb4-general_ci
        volumes:
           - /mysql/mysql-data:/var/lib/mysql
           - /mysql/conf.d:/etc/mysql/conf.d
           - /etc/localtime:/etc/localtime:ro
        ports :
                - 3306:3306
        restart: always
        environment:
          TZ: Asia/Shanghai
          MYSQL_ROOT_PASSWORD : "admin123"     #设置默认的root密码

